project:
  type: website
  output-dir: docs

website:
  title: "Nolan Dowling"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
            
  page-footer:
      left: |
        &copy; Nolan Dowling, 2024<br>
        All content licensed under <i class='bi-badge-cc'></i>
        [(CC BY-NC-SA 4.0)](http://creativecommons.org/licenses/by-nc-sa/4.0/)
      right: |
        Site built with <a href='https://quarto.org/'>Quarto</a>

format:
  html:
    theme: cyborg
    css: styles.css
    toc: true

editor: visual

