---
title: "Mini Project #1: Wisconsin"
sidebar: false
format:
  html: default
editor_options: 
  chunk_output_type: console
---

```{r, results='hide'}
#| message: false
#| warning: false

library(sf)
library(fs)
library(tidyverse)
library(lubridate)
devtools::install_github("baumer-lab/fec12")
library(fec12)
library(tidyverse)
library(mdsr) 
library(sf)
library(ggspatial)
library(prettymapr)

src <- "http://cdmaps.polisci.ucla.edu/shp/districts113.zip"
lcl_zip <- fs::path(tempdir(), "districts113.zip")
download.file(src, destfile = lcl_zip)
lcl_districts <- fs::path(tempdir(), "districts113")
unzip(lcl_zip, exdir = lcl_districts)
dsn_districts <- fs::path(lcl_districts, "districtShapes")

st_layers(dsn_districts)

districts <- st_read(dsn_districts, layer = "districts113") |>
  mutate(DISTRICT = parse_number(as.character(DISTRICT)))
head(districts, width = Inf)
class(districts)

wi_shp <- districts |>
  filter(STATENAME == "Wisconsin")

district_elections <- results_house |>
  mutate(district = parse_number(district_id)) |>
  group_by(state, district) |>
  summarize(
    N = n(), 
    total_votes = sum(general_votes, na.rm = TRUE),
    d_votes = sum(ifelse(party == "D", general_votes, 0), na.rm = TRUE),
    r_votes = sum(ifelse(party == "R", general_votes, 0), na.rm = TRUE),
    .groups = "drop"
  ) |>
  mutate(
    other_votes = total_votes - d_votes - r_votes,
    r_prop = r_votes / total_votes,  
    winner = ifelse(r_votes > d_votes, "Republican", "Democrat")
  )

wi_results <- district_elections |>
  filter(state == "WI") |>
  select(-state)

wi_merged <- wi_shp |>
  st_transform(4326) |>
  inner_join(wi_results, by = c("DISTRICT" = "district"))
head(wi_merged, width = Inf)

wi <- ggplot(data = wi_merged, aes(fill = winner)) +
  annotation_map_tile(zoom = 6, type = "osm", progress = "none") + 
  geom_sf(alpha = 0.5) +
  scale_fill_manual("Winner", values = c("blue", "red")) + 
  geom_sf_label(aes(label = DISTRICT), fill = "white") + 
  theme_void()
```


```{r}
library(leaflet)
pal <- colorNumeric(palette = "RdBu", domain = c(0, 1))

leaflet_wi <- leaflet(wi_merged) |>
  addTiles() |>
  addPolygons(
    weight = 1, fillOpacity = 0.7, 
    color = ~pal(1 - r_prop),   
    popup = ~paste("District", DISTRICT, "</br>", round(r_prop, 4))
  ) |>                     
  setView(lng = -90, lat = 44, zoom = 6)
leaflet_wi

```
